name: deploy website

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check out repo
        uses: actions/checkout@v2

      - name: use Node.js v16.13.2
        uses: actions/setup-node@v1
        with:
          node-version: v16.13.2

      - name: server - NPM install
        working-directory: ./api
        run: npm install

      - name: client - NPM install
        working-directory: ./client
        run: npm install

      - name: client - NPM build
        working-directory: ./client
        run: npm run build --if-present

      - name: Vercel Action
        uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
